config/routes.rb
Rails.application.routes.draw do  
  devise_for :users, :controllers => { registration: 'registrations' }
 
  resources :users, only: %i[index show]
  resources :categories, only: %i[show new create index]
  resources :articles, only: %i[new create update destroy show index edit] do 
    resources :votes, only: %i[index create destroy]
  end

  root 'articles#index'
end

app/models/article.rb
class Article < ApplicationRecord
  belongs_to :author, class_name: 'User'

  has_and_belongs_to_many :categories

  has_many :votes, dependent: :destroy

  has_one_attached :image

  validates :title, presence: true, length: { minimum: 5, maximum: 100 }
  validates :text, presence: true, length: { minimum: 5 }
  scope :ordered_by_most_recent, -> { order(created_at: :desc) }
  scope :most_popular, -> { find_by(votes_count: maximum(:votes_count)) }
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :set_article, only: %i[show edit update destroy]
  before_action :set_category, only: %i[create]
  before_action :authenticate_user!, except: %i[index show]

  # GET /articles or /articles.json
  def index
    @articles = Article.all
    @most_popular = @articles.most_popular
    @votes = Vote.all
    @popular = @votes.popular
  end

  # GET /articles/1 or /articles/1.json
  def show; end

  # GET /articles/new
  def new
    @article = Article.new
    @categories = Category.all
  end

  # GET /articles/1/edit
  def edit
    @categories = Category.all
    @article.image.attach(params[:image])
  end

  # POST /articles or /articles.json
  def create
    @article = current_user.articles.build(article_params)

    respond_to do |format|
      if @article.save
        @article.categories << Category.find(category_ids)
        format.html { redirect_to @article, notice: 'Article was successfully created.' }
        format.json { render :show, status: :created, location: @article }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /articles/1 or /articles/1.json
  def update
    respond_to do |format|
      if @article.update(article_params)
        format.html { redirect_to @article, notice: 'Article was successfully updated.' }
        format.json { render :show, status: :ok, location: @article }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /articles/1 or /articles/1.json
  def destroy
    @article.destroy
    respond_to do |format|
      format.html { redirect_to articles_url, notice: 'Article was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  def set_article
    @article = Article.find(params[:id])
    @categories = Category.all
  end

  def set_category
    @categories = Category.all
  end

  def article_params
    params.require(:article).permit(:title, :text, :image)
  end

  def category_ids
    params[:selected_id]
  end
end

app/helpers/articles_helper.rb
module ArticlesHelper
  def articles_controller(article)
    out = '<div class="is-flex">'
    if current_user.admin == true || current_user.id == article.author_id
      out += link_to 'Edit', edit_article_path(@article), class: 'button is-warning mr-2'
      out += button_to 'Delete', article, method: :delete, class: 'button is-danger mr-2'
    end
    out += '</div>'
    out.html_safe
  end

  def default_image(article)
    if article.image.attached?
      image_tag article.image
    else
      image_tag('/assets/news.jpg')
    end
  end

  def default_image_popular(article)
    if article.image.attached?
      image_tag article.image, class: 'article-main-image'
    else
      image_tag '/assets/news.jpg', class: 'article-main-image'
    end
  end

  def new_default_image(article)
    if article.image.attached?
      image_tag article.image, class: 'article-categories-image'
    else
      image_tag '/assets/news.jpg', class: 'article-categories-image'
    end
  end

  def show_new_article_list(_articles)
    out = ''
    @news = Category.find(1)
    @news.articles.each do |article|
      out += '<div class="column p-0 article-categories is-3">'
      out += '<div class="dummy"></div>'
      out += new_default_image(article)
      out += '</div>'
      out += '<div class="column p-5 article-news is-3 has-background-white has-text-main has-text-weight-bold">'
      out += '<h1 class="has-text-accent">News</h1>'
      out += "<h2 class=\"my-5 has-text-weight-semibold\">#{link_to article.title, article_url(article)}</h2>"
      out += "<p class=\"mb-5 has-text-weight-normal articles-news-main\">#{article.text}</p>"
      out += "<span class=\"mb-5 has-text-accent is-size-09 has-text-weight-normal\">#{link_to 'Read More',
                                                                                               article_url(article)}"
      out += '</span>'
      out += '</div>'
    end
    out.html_safe
  end

  def releases_default_image(article)
    if article.image.attached?
      image_tag article.image, class: 'article-categories-image'
    else
      image_tag '/assets/2021.jpg', class: 'article-categories-image'
    end
  end

  def show_releases_article_list(_articles)
    out = ''
    @releases = Category.find(4)
    @releases.articles.each do |article|
      out += '<div class="column p-5 article-news is-3 has-background-white has-text-main has-text-weight-bold">'
      out += '<h1 class="has-text-accent">Latest Releases</h1>'
      out += "<h2 class=\"my-5 has-text-weight-semibold\">#{link_to article.title, article_url(article)}</h2>"
      out += "<p class=\"mb-5 has-text-weight-normal articles-news-main\">#{article.text}</p>"
      out += "<span class=\"mb-5 has-text-accent is-size-09 has-text-weight-normal\">#{link_to 'Read More',
                                                                                               article_url(article)}"
      out += '</span>'
      out += '</div>'
      out += '<div class="column p-0 article-categories is-3">'
      out += '<div class="dummy"></div>'
      out += releases_default_image(article)
      out += '</div>'
    end
    out.html_safe
  end

  def show_patch_article_list(_articles)
    out = ''
    @patch = Category.find(3)
    @patch.articles.each do |article|
      out += "<li class=\"is-align-self-flex-end has-text-accent\">#{article.created_at.to_s(:time)}</li>"
      out += "<li class=\"mb-4\">#{link_to article.title, article_url(article),
                                           class: 'patch-link is-family-monospace is-uppercase'}</li>"
    end
    out.html_safe
  end

  def show_category(article)
    out = ''
    article.categories.each do |category|
      out += link_to category.name, category_url(category), class: 'button is-small is-main'
    end
    out.html_safe
  end
end

app/views/articles/_form.html.erb
<%= simple_form_for(@article) do |f| %>
  <%= f.error_notification %>
    <%= f.input :title, label: "Article title:", input_html: { class: "textarea"}, wrapper: false, label_html: {class: "label"}, placeholder: "Title here...", autofocus: true %>
    <br>
    <%= f.input :text, label: "Write your article:", input_html: { class: "textarea"}, wrapper: false, label_html: {class: "label"}, placeholder: "Article content here..." %>
    <br>
    <div class="columns">
      <div class="column">
        <%= f.input :image, label: "Select image:", input_html: { class: "file" }, wrapper: false, label_html: {class: "label"} %>
      </div>
      <div class="new-fields column is-flex p-0 pt-4 pl-4">
        <%= fields_for(@selected) do |s| %>
          <strong class="mr-4"><%= s.label :categories %>:</strong>
          <%= s.collection_select(:selected_id, @categories, :id, :name, {selected: 2, include_hidden: false}, { multiple: true, required: true }) %>
        <% end %>
      </div>
    </div>
    <br>
  <%= f.button :submit, class: "button is-main is-align-self-flex-start" %>
<% end %>

app/views/articles/_main.html.erb
<div class="main-text">
  <%= most_votes %>  
</div>

app/views/articles/edit.html.erb
<div class="new-container is-flex is-flex-direction-column is-align-items-center has-text-main">
  <section class="new-body">
  <h1 class="is-size-5 has-text-accent has-text-weight-bold mb-3">Editing Article</h1>

  <%= render 'form', article: @article %>

  <div class="is-flex mt-6">
    <%= link_to 'Cancel', @article, class: 'button is-danger mr-4 px-5 mt-5' %>
    <%= link_to 'Back to home', articles_path, class: 'button has-text-main is-outlined button-back-new mt-5' %>
  </div>
  </section>
</div>

app/views/articles/index.html.erb
<p id="notice"><%= notice %></p>

<div class="columns articles-home is-multiline mt-1">
  <%# MAIN IMAGE %>
  <div class="column p-0 article-main is-9">
    <section><%= render 'main' %></section>
    <%= most_votes_images %>
  </div>
  <%# EVENTS SECTION %>
  <div class="events-aside column p-0 article-side is-3">
    <section><%= render 'categories/events' %></section>
  </div>
  <%# FIRST %>
  <div class="column p-0 article-categories is-3">
    <section><%= render 'categories/first' %></section>
  </div>
  <%# SECOND %>
  <div class="column p-0 article-categories is-3">
    <section><%= render 'categories/second' %></section>
  </div>
  <%# THIRD %>
  <div class="column p-0 article-categories is-3">
    <section><%= render 'categories/third' %></section>
  </div>
  <%# FOURTH %>
  <div class="column p-0 article-categories is-3">
    <section><%= render 'categories/fourth' %></section>
  </div>
</div>

<%# CATEGORIES + PATCH NOTES %>
<div class="columns patch-notes my-6 ml-4 mr-2">
  <div class="column is-3 p-0 patch-aside-container my-2">
    <ul class="is-flex is-flex-direction-column px-6">
      <%= link_to 'Latest Patch Notes', category_path(Category.find(3)), class: 'has-text-accent has-text-weight-semibold is-family-monospace is-uppercase' %>
      <%= show_patch_article_list(@articles) %>
    </ul>
  </div>
  <div class="column is-6 patch-image-container p-0">
    <section><%= render 'categories/patch' %></section>
    <%= image_tag ("/assets/tft.jpg"), class:'patch-image' %>
  </div>
  <div class="column is-3 p-0 patch-aside-container my-2">
    <ul class="is-flex is-flex-direction-column px-6">
      <%= link_to 'Search by category:', categories_path, class: 'has-text-accent has-text-weight-semibold is-family-monospace is-uppercase mb-3' %>
      <%= show_all_categories %>
    </ul>
  </div>
</div>

<%# NEWS ARTICLES %>
<div class="columns articles-home">
  <%= show_new_article_list(@articles) %>
</div>
<div class="columns articles-home">
  <%= show_releases_article_list(@articles) %>
</div>

app/views/articles/new.html.erb
<div class="new-container is-flex is-flex-direction-column is-align-items-center has-text-main">
  <section class="new-body">
  <h1 class="is-size-5 has-text-accent has-text-weight-bold mb-3">New Article</h1>

  <%= render 'form', article: @article %>

  <%= link_to 'Back to home', articles_path, class: "button has-text-main is-align-self-center is-outlined button-back-new mt-2" %>
  </section>
</div>

app/views/articles/show.html.erb
<p id="notice"><%= notice %></p>

<div class="show-container is-flex is-flex-direction-column is-align-items-center has-text-main">
  <span class="is-align-self-flex-start mb-1"><%= show_category(@article) %></span>
  <h1 class="is-align-self-flex-start mb-1 is-size-4 has-text-weight-bold has-text-accent"><%= @article.title %></h1>
    <span class="is-align-self-flex-start mb-1 is-size-7 has-text-grey"><%= @article.created_at.to_date.iso8601 %></span>
  <div class="show-image"><%= default_image(@article) %></div>
  <div class="has-text-justified mt-6"><%= @article.text %></div>
  <div class="is-align-self-flex-start is-flex is-align-items-center my-5">
    <%= vote_button(@article) %>
    <span class="ml-2"><%= @article.votes.count %> <%= (@article.votes.count) == 1 ? 'Vote' : 'Votes' %></span>
  </div>
  <%= articles_controller(@article) %>
</div>